#
#  Do not edit this file.  This file is generated from 
#  package.bld.  Any modifications to this file will be 
#  overwritten whenever makefiles are re-generated.
#
#  target compatibility key = ti.targets.arm.elf.R4Ft{1,0,20.2,7
#
mmw_mss.xer4ft: package/cfg/mmw_mss.xer4ft.mak

clean::
	-$(RM) package/cfg/mmw_mss.xer4ft.mak
